# Generated by Django 5.2.13 on 2026-04-22 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ability",
            fields=[
                ("ability_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("ability_type", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "ability",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "diagnosis_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("code", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "diagnosis",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("job_role", models.TextField()),
                ("specialty", models.TextField(blank=True, null=True)),
                ("hire_date", models.DateField()),
                ("phone", models.TextField()),
                ("email", models.TextField()),
                ("schedule", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "employee",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("invoice_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.TextField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("issue_date", models.DateField()),
            ],
            options={
                "db_table": "invoice",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "line_item_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("line_item_type", models.TextField()),
                ("medication_id", models.BigIntegerField(blank=True, null=True)),
                ("vaccination_id", models.BigIntegerField(blank=True, null=True)),
                ("boarding_stay_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "line_item",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "observation_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("observation_type", models.TextField(blank=True, null=True)),
                (
                    "observed_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("unit", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "observation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                ("owner_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("phone", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "owner",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dob", models.DateField(blank=True, null=True)),
                ("name", models.TextField()),
                ("color", models.TextField(blank=True, null=True)),
                ("species_id", models.BigIntegerField(blank=True, null=True)),
                ("breed_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "patient",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PatientAbility",
            fields=[
                (
                    "patient_ability_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "patient_ability",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("payment_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_method", models.TextField()),
            ],
            options={
                "db_table": "payment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProcedureDefinition",
            fields=[
                (
                    "procedure_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "standard_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "procedure_definition",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Universe",
            fields=[
                ("universe_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "universe",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                ("visit_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "visit",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VisitDiagnosis",
            fields=[
                (
                    "visit_diagnosis_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("recorded_at", models.DateTimeField()),
            ],
            options={
                "db_table": "visit_diagnosis",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VisitProcedure",
            fields=[
                (
                    "visit_procedure_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("performed_at", models.DateTimeField()),
            ],
            options={
                "db_table": "visit_procedure",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CareNote",
            fields=[
                (
                    "care_note_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_notes",
                        to="mythical_app.patient",
                    ),
                ),
            ],
            options={
                "db_table": "care_note",
            },
        ),
    ]
